[tool.poetry]
name = "project-h10"
version = "0.1.0"
description = ""
authors = []

[tool.poetry.dependencies]
python = "^3.11"
mbed-tools = "^7.59.0"
prettytable = "^3.7.0"
future = "^0.18.3"
intelhex = "^2.3.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
